### ISSUE TITLE
Multiple permission levels

### ISSUE THREAD

**Issue by TheKodeToad** [TheKodeToad/Letterbox#9]
Something simple like
```toml
[[roles]]
name = "Moderator"
ids = [1256671609863933962]
reply = true
close = true
```
